/*  vars.h - extern definitions for global variables
*
*   Author:
*	Benjamin W. Slivka
*	(c) 1987,1988
*	Microsoft Corporation
*
*   History:
*	17-Aug-1987 bws Add this header
*	13-Feb-1988 bws Add fColor flag
*/

/*  NOTE: see vars.c for definitions */

extern int	N_of_Cols;
extern int	N_of_Rows;

extern int	dataRows;

extern int	color[];
extern int	cColors;

extern int	fDebug;
extern int	fXDebug;
extern int	fFile;
extern int	fProfile;
extern int	fRecord;
extern int	f43mode;
extern int	fColor;

extern dword	refreshPeriod;
